### ISSUE TITLE
Thanks for this project!

### ISSUE THREAD

**Issue by DavertMik** [marcuxyz/curlify#4]
I just discovered it and it seems it can fix all our client requests like: "connection not work, help!!!111". So they could use CURL to verify if their configuration is valid.

I didn't try this gem yet but I'm really excited to find it. I see it doesn't have lot of stars so I decided to write this message😍

Thanks, @marcuxyz

**Comment by marcuxyz** [comment]
@DavertMik thanks for comment. I'm very happy to know this. I'm very happy for help u.
